# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.link_by_products import LinkByProducts  # noqa: E501
from grafeas.rest import ApiException


class TestLinkByProducts(unittest.TestCase):
    """LinkByProducts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkByProducts(self):
        """Test LinkByProducts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.link_by_products.LinkByProducts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
