# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.build_signature_key_type import BuildSignatureKeyType  # noqa: E501
from grafeas.rest import ApiException


class TestBuildSignatureKeyType(unittest.TestCase):
    """BuildSignatureKeyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildSignatureKeyType(self):
        """Test BuildSignatureKeyType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.build_signature_key_type.BuildSignatureKeyType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
