# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.spdx_relationship_occurrence import SpdxRelationshipOccurrence  # noqa: E501
from grafeas.rest import ApiException


class TestSpdxRelationshipOccurrence(unittest.TestCase):
    """SpdxRelationshipOccurrence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpdxRelationshipOccurrence(self):
        """Test SpdxRelationshipOccurrence"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.spdx_relationship_occurrence.SpdxRelationshipOccurrence()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
