# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.spdx_license import SpdxLicense  # noqa: E501
from grafeas.rest import ApiException


class TestSpdxLicense(unittest.TestCase):
    """SpdxLicense unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpdxLicense(self):
        """Test SpdxLicense"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.spdx_license.SpdxLicense()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
