# coding: utf-8

"""
    project.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.project_list_projects_response import ProjectListProjectsResponse  # noqa: E501
from grafeas.rest import ApiException


class TestProjectListProjectsResponse(unittest.TestCase):
    """ProjectListProjectsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectListProjectsResponse(self):
        """Test ProjectListProjectsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.project_list_projects_response.ProjectListProjectsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
