# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.v1beta1intoto_details import V1beta1intotoDetails  # noqa: E501
from grafeas.rest import ApiException


class TestV1beta1intotoDetails(unittest.TestCase):
    """V1beta1intotoDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1intotoDetails(self):
        """Test V1beta1intotoDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.v1beta1intoto_details.V1beta1intotoDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
