# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.v1beta1_envelope import V1beta1Envelope  # noqa: E501
from grafeas.rest import ApiException


class TestV1beta1Envelope(unittest.TestCase):
    """V1beta1Envelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1Envelope(self):
        """Test V1beta1Envelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.v1beta1_envelope.V1beta1Envelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
