# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import grafeas
from grafeas.models.in_toto_artifact_rule import InTotoArtifactRule  # noqa: E501
from grafeas.rest import ApiException


class TestInTotoArtifactRule(unittest.TestCase):
    """InTotoArtifactRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInTotoArtifactRule(self):
        """Test InTotoArtifactRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = grafeas.models.in_toto_artifact_rule.InTotoArtifactRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
