# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InTotoArtifactRule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'artifact_rule': 'list[str]'
    }

    attribute_map = {
        'artifact_rule': 'artifactRule'
    }

    def __init__(self, artifact_rule=None):  # noqa: E501
        """InTotoArtifactRule - a model defined in Swagger"""  # noqa: E501

        self._artifact_rule = None
        self.discriminator = None

        if artifact_rule is not None:
            self.artifact_rule = artifact_rule

    @property
    def artifact_rule(self):
        """Gets the artifact_rule of this InTotoArtifactRule.  # noqa: E501


        :return: The artifact_rule of this InTotoArtifactRule.  # noqa: E501
        :rtype: list[str]
        """
        return self._artifact_rule

    @artifact_rule.setter
    def artifact_rule(self, artifact_rule):
        """Sets the artifact_rule of this InTotoArtifactRule.


        :param artifact_rule: The artifact_rule of this InTotoArtifactRule.  # noqa: E501
        :type: list[str]
        """

        self._artifact_rule = artifact_rule

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InTotoArtifactRule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InTotoArtifactRule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
