# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PackageInfoNoteExternalRef(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'ExternalRefCategory',
        'type': 'str',
        'locator': 'str',
        'comment': 'str'
    }

    attribute_map = {
        'category': 'category',
        'type': 'type',
        'locator': 'locator',
        'comment': 'comment'
    }

    def __init__(self, category=None, type=None, locator=None, comment=None):  # noqa: E501
        """PackageInfoNoteExternalRef - a model defined in Swagger"""  # noqa: E501

        self._category = None
        self._type = None
        self._locator = None
        self._comment = None
        self.discriminator = None

        if category is not None:
            self.category = category
        if type is not None:
            self.type = type
        if locator is not None:
            self.locator = locator
        if comment is not None:
            self.comment = comment

    @property
    def category(self):
        """Gets the category of this PackageInfoNoteExternalRef.  # noqa: E501


        :return: The category of this PackageInfoNoteExternalRef.  # noqa: E501
        :rtype: ExternalRefCategory
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this PackageInfoNoteExternalRef.


        :param category: The category of this PackageInfoNoteExternalRef.  # noqa: E501
        :type: ExternalRefCategory
        """

        self._category = category

    @property
    def type(self):
        """Gets the type of this PackageInfoNoteExternalRef.  # noqa: E501


        :return: The type of this PackageInfoNoteExternalRef.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PackageInfoNoteExternalRef.


        :param type: The type of this PackageInfoNoteExternalRef.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def locator(self):
        """Gets the locator of this PackageInfoNoteExternalRef.  # noqa: E501


        :return: The locator of this PackageInfoNoteExternalRef.  # noqa: E501
        :rtype: str
        """
        return self._locator

    @locator.setter
    def locator(self, locator):
        """Sets the locator of this PackageInfoNoteExternalRef.


        :param locator: The locator of this PackageInfoNoteExternalRef.  # noqa: E501
        :type: str
        """

        self._locator = locator

    @property
    def comment(self):
        """Gets the comment of this PackageInfoNoteExternalRef.  # noqa: E501


        :return: The comment of this PackageInfoNoteExternalRef.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this PackageInfoNoteExternalRef.


        :param comment: The comment of this PackageInfoNoteExternalRef.  # noqa: E501
        :type: str
        """

        self._comment = comment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackageInfoNoteExternalRef, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackageInfoNoteExternalRef):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
