# coding: utf-8

"""
    grafeas.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SpdxFileNote(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'file_type': 'FileNoteFileType',
        'checksum': 'list[str]'
    }

    attribute_map = {
        'title': 'title',
        'file_type': 'fileType',
        'checksum': 'checksum'
    }

    def __init__(self, title=None, file_type=None, checksum=None):  # noqa: E501
        """SpdxFileNote - a model defined in Swagger"""  # noqa: E501

        self._title = None
        self._file_type = None
        self._checksum = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if file_type is not None:
            self.file_type = file_type
        if checksum is not None:
            self.checksum = checksum

    @property
    def title(self):
        """Gets the title of this SpdxFileNote.  # noqa: E501


        :return: The title of this SpdxFileNote.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this SpdxFileNote.


        :param title: The title of this SpdxFileNote.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def file_type(self):
        """Gets the file_type of this SpdxFileNote.  # noqa: E501


        :return: The file_type of this SpdxFileNote.  # noqa: E501
        :rtype: FileNoteFileType
        """
        return self._file_type

    @file_type.setter
    def file_type(self, file_type):
        """Sets the file_type of this SpdxFileNote.


        :param file_type: The file_type of this SpdxFileNote.  # noqa: E501
        :type: FileNoteFileType
        """

        self._file_type = file_type

    @property
    def checksum(self):
        """Gets the checksum of this SpdxFileNote.  # noqa: E501


        :return: The checksum of this SpdxFileNote.  # noqa: E501
        :rtype: list[str]
        """
        return self._checksum

    @checksum.setter
    def checksum(self, checksum):
        """Sets the checksum of this SpdxFileNote.


        :param checksum: The checksum of this SpdxFileNote.  # noqa: E501
        :type: list[str]
        """

        self._checksum = checksum

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SpdxFileNote, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SpdxFileNote):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
